module.exports = {
    phrase: [ 'generate', 'reveal', 'checkPwd', 'has', 'import', 'reset'],
    wallet: [ 'lock', 'unlock', 'checkUpdateDB', 'getPubKey', 'connectToLedger', 'deleteLedger', 'isConnected', 'getPubKeyChainId', 'signPersonalMessage', 'signTransaction', 'setUserTblVersion', 'reboot', 'exportPrivateKeys', 'importPrivateKey', 'signTx' ],
    address: [ 'get', 'getOne', 'getNonce', 'balance', 'balances', 'getPrivateTxInfo', 'scanMultiOTA', 'isWanAddress', 'isXrpAddress', 'fromKeyFile', 'getKeyStoreCount', 'isValidatorAddress', 'ethBalance', 'isEthAddress', 'btcImportAddress', 'getBtcMultiBalances', 'btcCoinSelect', 'getEosAccountInfo', 'getEOSResourcePrice', 'getRamPrice', 'isEosPublicKey', 'isEosNameExist', 'getNewPathIndex', 'getNewNameForNativeAccount', 'isValidPrivateKey' ],
    account: [ 'create', 'get', 'getAllAccounts', 'getAll', 'update', 'delete', 'getAccountByPublicKey', 'setImportedUserAccounts', 'getImportedAccountsByPublicKey', 'getAccountStakeInfo', 'deleteEOSImportedAccounts' ],
    transaction: [ 'normal', 'private', 'refund', 'raw', 'estimateGas', 'showRecords', 'insertTransToDB', 'BTCNormal', 'XRPNormal', 'EOSNormal', 'tokenNormal', 'estimateSmartFee' ],
    query: [ 'config', 'getGasPrice' ],
    staking: [ 'getContractAddr', 'info', 'delegateIn', 'delegateOut', 'getContractData', 'insertTransToDB', 'posInfo', 'registerValidator', 'insertRegisterValidatorToDB', 'validatorInfo', 'validatorAppend', 'validatorUpdate', 'getValidatorsInfo', 'getCurrentEpochInfo', 'PosStakeUpdateFeeRate' ],
    setting: ['switchNetwork', 'set', 'get', 'updateDapps', 'getDapps', 'getDAppInjectFile', 'rpcDelay', 'wanNodeDelay', 'ethNodeDelay', 'btcNodeDelay', 'eosNodeDelay', 'resetSettingsByOptions'],
    crossChain: ['getTokensInfo', 'getTokenPairs', 'getChainInfoByChainId', 'getCcTokenSelections', 'setCcTokenSelectStatus', 'updateTokensInfo', 'updateTokensBalance', 'getTokenInfo', 'addCustomToken', 'deleteCustomToken', 'getSmgList', 'getStoremanGroupList', 'getStoremanGroupListByChainPair', 'getHtmlAddr', 'getCrossChainContractData', 'crossChain', 'crossBTC', 'crossETH', 'crossEOS', 'crossEOS2WAN', 'getAllUndoneCrossTrans', 'increaseFailedRetryCount', 'getAllCrossTrans', 'getRegisteredOrigToken', 'getMintQuota', 'getBurnQuota', 'getQuota', 'getFastMinCount', 'getFees'],
    dappStore: ['getRegisteredDapp', 'getRegisteredAds'],
    upgrade: ['start'],
    contract: ['sendTx','setFilePath','getOutputPath','buildTx','updateNonce'],
    storeman: ['getRewardRatio', 'getMultiStoremanGroupInfo', 'getSelectedStoreman', 'publicToAddress', 'getStoremanConf', 'getStoremanDelegatorTotalIncentive', 'getStoremanStakeTotalIncentive', 'getStoremanDelegators', 'openStoremanAction', 'getContractData', 'insertStoremanTransToDB', 'getOpenStoremanGroupList', 'getReadyOpenStoremanGroupList', 'getStoremanStakeInfo', 'getStoremanDelegatorInfo', 'getStoremanGroupMember', 'getStoremanCandidates'],
  }
